/* ==========================================
   服务 worker - 应用壳缓存 + 离线缓存 + 重连合并
   版本升级后旧缓存自动清理；data/ 走 network-first 保证重连后拿到云端最新数据
   ========================================== */
const CACHE = 'you-workbench-v8';
const ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './favicon.ico',
  './css/styles.css',
  './css/items.css',
  './css/words.css',
  './js/app.js',
  './js/items.js',
  './js/words-db.js',
  './js/words-ui.js',
  './sw.js',
  './assets/apple-touch-icon.png',
  './assets/icon-192.png',
  './assets/icon-512.png',
  './assets/icon-maskable-512.png',
  './assets/icon.svg',
  './data/hot-videos.json',
  './data/topic-bilibili.json',
  './data/topic-douyin.json',
  './data/topic-xiaohongshu.json',
  './assets/items/icons/sys_appliance_冰箱.png',
  './assets/items/icons/sys_appliance_加湿器.png',
  './assets/items/icons/sys_appliance_吸尘器.png',
  './assets/items/icons/sys_appliance_吹风机.png',
  './assets/items/icons/sys_appliance_咖啡机.png',
  './assets/items/icons/sys_appliance_微波炉.png',
  './assets/items/icons/sys_appliance_扫地机器人.png',
  './assets/items/icons/sys_appliance_油烟机.png',
  './assets/items/icons/sys_appliance_洗地机.png',
  './assets/items/icons/sys_appliance_洗碗机.png',
  './assets/items/icons/sys_appliance_洗衣机.png',
  './assets/items/icons/sys_appliance_烘干机.png',
  './assets/items/icons/sys_appliance_烤箱.png',
  './assets/items/icons/sys_appliance_热水器.png',
  './assets/items/icons/sys_appliance_电磁炉.png',
  './assets/items/icons/sys_appliance_电视.png',
  './assets/items/icons/sys_appliance_电风扇.png',
  './assets/items/icons/sys_appliance_电饭煲.png',
  './assets/items/icons/sys_appliance_破壁机.png',
  './assets/items/icons/sys_appliance_空气净化器.png',
  './assets/items/icons/sys_appliance_空气炸锅.png',
  './assets/items/icons/sys_appliance_空调.png',
  './assets/items/icons/sys_asset_住宅.png',
  './assets/items/icons/sys_asset_公寓.png',
  './assets/items/icons/sys_asset_其他资产.png',
  './assets/items/icons/sys_asset_商铺.png',
  './assets/items/icons/sys_asset_车位.png',
  './assets/items/icons/sys_asset_车辆.png',
  './assets/items/icons/sys_baby_其他.png',
  './assets/items/icons/sys_baby_奶瓶.png',
  './assets/items/icons/sys_baby_婴儿床.png',
  './assets/items/icons/sys_baby_婴儿车.png',
  './assets/items/icons/sys_baby_孕妈用品.png',
  './assets/items/icons/sys_baby_安全座椅.png',
  './assets/items/icons/sys_baby_湿巾.png',
  './assets/items/icons/sys_baby_玩具.png',
  './assets/items/icons/sys_baby_童装.png',
  './assets/items/icons/sys_baby_童鞋.png',
  './assets/items/icons/sys_baby_纸尿裤.png',
  './assets/items/icons/sys_baby_绘本.png',
  './assets/items/icons/sys_baby_配方奶粉.png',
  './assets/items/icons/sys_beauty_乳液.png',
  './assets/items/icons/sys_beauty_其他.png',
  './assets/items/icons/sys_beauty_剃须刀.png',
  './assets/items/icons/sys_beauty_口腔健康.png',
  './assets/items/icons/sys_beauty_女性护理.png',
  './assets/items/icons/sys_beauty_彩妆.png',
  './assets/items/icons/sys_beauty_时尚配饰.png',
  './assets/items/icons/sys_beauty_洁面.png',
  './assets/items/icons/sys_beauty_洗发护发.png',
  './assets/items/icons/sys_beauty_爽肤水.png',
  './assets/items/icons/sys_beauty_眼霜.png',
  './assets/items/icons/sys_beauty_精华.png',
  './assets/items/icons/sys_beauty_身体护理.png',
  './assets/items/icons/sys_beauty_防晒.png',
  './assets/items/icons/sys_beauty_面膜.png',
  './assets/items/icons/sys_beauty_面霜.png',
  './assets/items/icons/sys_beauty_香水.png',
  './assets/items/icons/sys_clothing_T恤.png',
  './assets/items/icons/sys_clothing_内衣.png',
  './assets/items/icons/sys_clothing_半身裙.png',
  './assets/items/icons/sys_clothing_卫衣.png',
  './assets/items/icons/sys_clothing_双肩包.png',
  './assets/items/icons/sys_clothing_围巾.png',
  './assets/items/icons/sys_clothing_外套.png',
  './assets/items/icons/sys_clothing_帽子.png',
  './assets/items/icons/sys_clothing_手套.png',
  './assets/items/icons/sys_clothing_手提包.png',
  './assets/items/icons/sys_clothing_拖鞋.png',
  './assets/items/icons/sys_clothing_毛衣.png',
  './assets/items/icons/sys_clothing_牛仔裤.png',
  './assets/items/icons/sys_clothing_皮带.png',
  './assets/items/icons/sys_clothing_羽绒服.png',
  './assets/items/icons/sys_clothing_衬衫.png',
  './assets/items/icons/sys_clothing_袜子.png',
  './assets/items/icons/sys_clothing_裤子.png',
  './assets/items/icons/sys_clothing_西装.png',
  './assets/items/icons/sys_clothing_运动鞋.png',
  './assets/items/icons/sys_clothing_连衣裙.png',
  './assets/items/icons/sys_clothing_钱包.png',
  './assets/items/icons/sys_clothing_雨鞋.png',
  './assets/items/icons/sys_clothing_靴子.png',
  './assets/items/icons/sys_collection_乐器.png',
  './assets/items/icons/sys_collection_其他.png',
  './assets/items/icons/sys_collection_卡牌.png',
  './assets/items/icons/sys_collection_唱片.png',
  './assets/items/icons/sys_collection_徽章.png',
  './assets/items/icons/sys_collection_手办.png',
  './assets/items/icons/sys_collection_模型.png',
  './assets/items/icons/sys_collection_纪念币.png',
  './assets/items/icons/sys_collection_艺术品.png',
  './assets/items/icons/sys_collection_邮票.png',
  './assets/items/icons/sys_digital_CPU.png',
  './assets/items/icons/sys_digital_NAS.png',
  './assets/items/icons/sys_digital_U盘.png',
  './assets/items/icons/sys_digital_主板.png',
  './assets/items/icons/sys_digital_充电宝.png',
  './assets/items/icons/sys_digital_内存.png',
  './assets/items/icons/sys_digital_加湿器.png',
  './assets/items/icons/sys_digital_台式电脑.png',
  './assets/items/icons/sys_digital_固态硬盘.png',
  './assets/items/icons/sys_digital_存储卡.png',
  './assets/items/icons/sys_digital_平板电脑.png',
  './assets/items/icons/sys_digital_手机.png',
  './assets/items/icons/sys_digital_打印机.png',
  './assets/items/icons/sys_digital_投影仪.png',
  './assets/items/icons/sys_digital_散热器.png',
  './assets/items/icons/sys_digital_无人机.png',
  './assets/items/icons/sys_digital_显卡.png',
  './assets/items/icons/sys_digital_显示器.png',
  './assets/items/icons/sys_digital_智能手表.png',
  './assets/items/icons/sys_digital_智能眼镜.png',
  './assets/items/icons/sys_digital_机箱.png',
  './assets/items/icons/sys_digital_游戏机.png',
  './assets/items/icons/sys_digital_电子书.png',
  './assets/items/icons/sys_digital_电源.png',
  './assets/items/icons/sys_digital_相机.png',
  './assets/items/icons/sys_digital_硬盘.png',
  './assets/items/icons/sys_digital_笔记本电脑.png',
  './assets/items/icons/sys_digital_耳机.png',
  './assets/items/icons/sys_digital_路由器.png',
  './assets/items/icons/sys_digital_键盘.png',
  './assets/items/icons/sys_digital_镜头.png',
  './assets/items/icons/sys_digital_音箱.png',
  './assets/items/icons/sys_digital_音频设备.png',
  './assets/items/icons/sys_digital_风扇.png',
  './assets/items/icons/sys_digital_鼠标.png',
  './assets/items/icons/sys_hardware_其他.png',
  './assets/items/icons/sys_hardware_地板.png',
  './assets/items/icons/sys_hardware_墙纸.png',
  './assets/items/icons/sys_hardware_家装工具.png',
  './assets/items/icons/sys_hardware_开关插座.png',
  './assets/items/icons/sys_hardware_水槽.png',
  './assets/items/icons/sys_hardware_水龙头.png',
  './assets/items/icons/sys_hardware_油漆.png',
  './assets/items/icons/sys_hardware_瓷砖.png',
  './assets/items/icons/sys_hardware_花洒.png',
  './assets/items/icons/sys_hardware_门锁.png',
  './assets/items/icons/sys_hardware_马桶.png',
  './assets/items/icons/sys_home_其他.png',
  './assets/items/icons/sys_home_厨具.png',
  './assets/items/icons/sys_home_家纺.png',
  './assets/items/icons/sys_home_床.png',
  './assets/items/icons/sys_home_床垫.png',
  './assets/items/icons/sys_home_收纳.png',
  './assets/items/icons/sys_home_柜子.png',
  './assets/items/icons/sys_home_桌子.png',
  './assets/items/icons/sys_home_椅子.png',
  './assets/items/icons/sys_home_沙发.png',
  './assets/items/icons/sys_home_洗衣用品.png',
  './assets/items/icons/sys_home_清洁品.png',
  './assets/items/icons/sys_home_灯具.png',
  './assets/items/icons/sys_home_茶几.png',
  './assets/items/icons/sys_home_衣架.png',
  './assets/items/icons/sys_home_雨伞.png',
  './assets/items/icons/sys_home_餐具.png',
  './assets/items/icons/sys_medical_体温计.png',
  './assets/items/icons/sys_medical_体重秤.png',
  './assets/items/icons/sys_medical_其他.png',
  './assets/items/icons/sys_medical_助听器.png',
  './assets/items/icons/sys_medical_医学美容.png',
  './assets/items/icons/sys_medical_急救用品.png',
  './assets/items/icons/sys_medical_手术治疗.png',
  './assets/items/icons/sys_medical_按摩器械.png',
  './assets/items/icons/sys_medical_眼镜.png',
  './assets/items/icons/sys_medical_药品.png',
  './assets/items/icons/sys_medical_血压计.png',
  './assets/items/icons/sys_medical_血糖仪.png',
  './assets/items/icons/sys_medical_隐形眼镜.png',
  './assets/items/icons/sys_office_书写用品.png',
  './assets/items/icons/sys_office_书籍.png',
  './assets/items/icons/sys_office_其他.png',
  './assets/items/icons/sys_office_办公用品.png',
  './assets/items/icons/sys_office_收纳用品.png',
  './assets/items/icons/sys_office_绘画工具.png',
  './assets/items/icons/sys_office_胶粘用品.png',
  './assets/items/icons/sys_office_裁剪用品.png',
  './assets/items/icons/sys_office_计算器.png',
  './assets/items/icons/sys_other_礼品.png',
  './assets/items/icons/sys_other_票券.png',
  './assets/items/icons/sys_outdoor_健身器材.png',
  './assets/items/icons/sys_outdoor_天幕.png',
  './assets/items/icons/sys_outdoor_帐篷.png',
  './assets/items/icons/sys_outdoor_徒步登山.png',
  './assets/items/icons/sys_outdoor_攀岩用品.png',
  './assets/items/icons/sys_outdoor_游泳用品.png',
  './assets/items/icons/sys_outdoor_滑雪用品.png',
  './assets/items/icons/sys_outdoor_球（拍）类.png',
  './assets/items/icons/sys_outdoor_电器照明.png',
  './assets/items/icons/sys_outdoor_睡袋.png',
  './assets/items/icons/sys_outdoor_钓鱼用品.png',
  './assets/items/icons/sys_outdoor_防护救生.png',
  './assets/items/icons/sys_pet_其他.png',
  './assets/items/icons/sys_pet_宠物包.png',
  './assets/items/icons/sys_pet_宠物服饰.png',
  './assets/items/icons/sys_pet_宠物玩具.png',
  './assets/items/icons/sys_pet_宠物窝.png',
  './assets/items/icons/sys_pet_宠物粮.png',
  './assets/items/icons/sys_pet_洗护用品.png',
  './assets/items/icons/sys_pet_牵引绳.png',
  './assets/items/icons/sys_pet_猫砂.png',
  './assets/items/icons/sys_pet_食盆.png',
  './assets/items/icons/sys_service_保险服务.png',
  './assets/items/icons/sys_service_其他服务.png',
  './assets/items/icons/sys_service_课程培训.png',
  './assets/items/icons/sys_transport_其他.png',
  './assets/items/icons/sys_transport_头盔.png',
  './assets/items/icons/sys_transport_摩托车.png',
  './assets/items/icons/sys_transport_电动车.png',
  './assets/items/icons/sys_transport_自行车.png',
  './assets/items/icons/sys_transport_行李箱.png',
  './assets/items/icons/sys_transport_转换插头.png',
  './assets/items/icons/sys_transport_颈枕.png',
  './assets/items/icons/sys_vehicle_其他.png',
  './assets/items/icons/sys_vehicle_座套.png',
  './assets/items/icons/sys_vehicle_机油.png',
  './assets/items/icons/sys_vehicle_洗车用品.png',
  './assets/items/icons/sys_vehicle_电瓶.png',
  './assets/items/icons/sys_vehicle_脚垫.png',
  './assets/items/icons/sys_vehicle_行车记录仪.png',
  './assets/items/icons/sys_vehicle_车载充电器.png',
  './assets/items/icons/sys_vehicle_车载吸尘器.png',
  './assets/items/icons/sys_vehicle_车载支架.png',
  './assets/items/icons/sys_vehicle_车载香薰.png',
  './assets/items/icons/sys_vehicle_轮胎.png',
  './assets/items/icons/sys_vehicle_雨刮器.png',
  './assets/items/icons/sys_virtual_会员订阅.png',
  './assets/items/icons/sys_virtual_其他虚拟.png',
  './assets/items/icons/sys_virtual_游戏点卡.png'
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);

  // data/ 目录：network-first，离线时回退缓存（重连后自动拿最新）
  if (url.pathname.includes('/data/')) {
    event.respondWith(
      fetch(event.request).then(resp => {
        if (resp && resp.status === 200) {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(event.request, copy));
        }
        return resp;
      }).catch(() => caches.match(event.request).then(c => c || caches.match('./index.html')))
    );
    return;
  }

  // 应用壳：cache-first，命中即返回；未命中再走网络并缓存
  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) return cached;
      return fetch(event.request).then(resp => {
        if (resp && resp.status === 200 && resp.type === 'basic') {
          const copy = resp.clone();
          caches.open(CACHE).then(cache => cache.put(event.request, copy));
        }
        return resp;
      }).catch(() => caches.match('./index.html'));
    })
  );
});
